version: '3'
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  backend:
    build:
      context: ./packages/backend
    command: npm start
    environment:
      NODE_ENV: production
    restart: always
  frontend:
    build:
      context: ./packages/frontend
    command: npm start
    environment:
      NODE_ENV: production
    restart: always
