service:
  name: auth

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    stage: ${opt:stage, self:provider.stage}

functions:
  auth:
    handler: index.handler
  test:
    handler: index.test
    events:
      - http:
          method: get
          path: /test
          authorizer:
            name: auth
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
  domains:
    prod: authorize.aidemaster.com
    staging: staging-authorize.aidemaster.com
    dev: dev-authorize.aidemaster.com

  customDomain:
    domainName: ${self:custom.domains.${self:provider.environment.stage}} # Change this to your domain.
    basePath: 'auth' # This will be prefixed to all routes
    stage: ${self:provider.environment.stage}
    createRoute53Record: true